---
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 3.67.172.240
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/ssh_frankfurt.pem
kibana:
  hosts:
    k-instance:
      ansible_host: 3.68.72.220
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/ssh_frankfurt.pem
app:
  hosts:
    application-instance:
      ansible_host: 3.70.137.115
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/ssh_frankfurt.pem